import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Sidebar from '@/components/Sidebar'
import getDummyData from '../data'

export default function Home(props) {
  const { products } = props
  const onClickHandler = (e) =>{
    e.preventDefault();
  }
  return (
    <>
      <Head>
        <title>Shopping App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className='PageGirdContainer'> */}
      <div className='PageContainer'>
        {/* <Sidebar /> */}
        <div className="productList">
          <h3>Home</h3>
          <div className="productsGrid">
            {products?.map((product) => {
              return (
                <Link key={product.productId}
                  href={`/products/${product.productId}`}
                  className={"card"}
                >
                  <Image src={product.image} width={236} height={142} alt={product.name} />
                  <h2>
                    {product.name}
                  </h2>
                  <p>
                    ${product.price}
                  </p>
                  <button onClick={onClickHandler}>Add to cart</button>
                </Link>
              )
            })}
          </div>
        </div>
      </div>
    </>
  )
}

export async function getStaticProps(context) {
  const products = getDummyData()
  return {
    props: {
      products
    }
  }
}